version: "3"
services:
  poll:
    build: ./poll/.
    restart: always
    ports: 
      - "5000:80"
    networks: 
      - poll-tier
  redis:
    image: "redis:latest"
    restart: always
    ports: 
      - "6379:6379"
    networks: 
      - back-tier
      - poll-tier
  worker:
    build: ./worker/.
    networks: 
      - back-tier
  db:
    image: "postgres:latest"
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes: 
      - db-data:/var/postgresql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks: 
      - back-tier
      - result-tier
  result:
    build: ./result/.
    restart: always
    ports: 
      - "5001:80"
    networks: 
      - result-tier
volumes: 
  db-data:
networks: 
  poll-tier:
  result-tier:
  back-tier: